services:
  veterinaria2024:
    build: D:\Programacion\cursoSpringBoot\veterinaria2024
    mem_limit: 212m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://clinica_vet:3306/Veterinaria2024?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: admin
      DB_PASSWORD: admin
    restart: always
    depends_on:
      clinica_vet:
        condition: service_healthy
  clinica_vet:
    image: mysql:8.2.0
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: Veterinaria2024
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
